L = 8
filling = 0.5
seed = 0
tol_sc = 1e-17
t = 0.2
U = 0.33
thetas = "12 -12 12 -12"
phis = "0 0 0 0"
alpha_mono = 0.0
lambda = 0.5
Delta = -0.15
eta2 = 0.2
eta_a = 1.0
eta3 = 0.0
etaz = 0.9
etaz2 = 0.0
etaz3 = 0.0
eta2_J05 = -0.7
n_kpoints = 64
k_route_type = 0
random_initialization = true
