L = 32
filling = 0.5
solve_self_consistent_equation = true
tol_sc = 1e-16
random_initialization = true
seed = 92912
t = 0.2
U = 0.6
thetas = "16 -16 16 -16"
phis = "10 -10 10 -10"
alpha_mono = 0.024062906180242
lambda = 0.5
Delta = -0.15
eta2 = 0.2
eta_a = 0.8
eta3 = 0.0
etaz = 1.0
etaz2 = 0.0
etaz3 = 0.0
eta2_J05 = -2.0
n_kpoints = 64
k_route_type = 0
mag1 = "0.0 0.0 0.5"
mag2 = "0.0 0.0 -0.5"
mag3 = "0.0 0.0 0.5"
mag4 = "0.0 0.0 -0.5"
